# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Presubmit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Presubmit
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'FirebaseUI/Google'


  target 'PresubmitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PresubmitUITests' do
    # Pods for testing
  end

end
